### 회원가입
POST {{host_api}}/signup
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "tnswh2023@",
  "name": "sunjo",
  "provider": "LOCAL"
}

### 로그인
POST {{host_api}}/login
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "tnswh2023@"
}
> {%
client.global.set('AUTH', response.body.data)
client.log(client.global.get('AUTH'));
 %}


### 내 정보 불러오기
GET {{host_api}}/api/v1/myInfo
Content-Type: application/json
Authorization: {{AUTH}}

### 내 정보 수정하기
PUT {{host_api}}/api/v1/myInfo/update
Content-Type: application/json
Authorization: {{AUTH}}

{
  "name": "name",
  "velogName": "velogName",
  "description": "description"
}