### file upload
POST {{host_api}}/image/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat.jpg"

< /Users/yusunjo/Desktop/Test.png
--WebAppBoundary--