server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
    ### application-aaa를 사용할 필요가 없어짐
    import:
      - application-domain.yml
      - jwt.yml
      - aws.yml
      - credentials.yml