
server:
  port: 8080
  address: 3.38.124.11
spring:
  config:
    activate:
      on-profile: local, dev
    ### application-aaa를 사용할 필요가 없어짐
    import:
      - application-domain.yml
      - aws.yml
      - jwt.properties
      - credentials.yml
      - auth.yml

logging:
  level:
    root: INFO