
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local, dev
    ### application-aaa를 사용할 필요가 없어짐
    import:
      - aws.yml
      - jwt.properties
      - credentials.properties
      - auth.properties

logging:
  level:
    root: INFO