server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local, prod
    ### application-aaa를 사용할 필요가 없어짐
    import:
      - application-domain.yml
      - jwt.yml
      - aws.yml
      - credentials.yml
      - auth.yml
      - rds.yml

logging:
  level:
    root: INFO