#spring.datasource.url=jdbc:mariadb://velog.cqa7rhjwuoqr.ap-northeast-2.rds.amazonaws.com/cavel
#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=147asdfg
#spring.jpa.databasePlatform=org.hibernate.dialect.MariaDB103Dialect
#spring.jpa.hibernate.ddlAuto=update
##spring.flyway.enabled=false
##spring.flyway.baseline-on-migrate=true
##spring.flyway.baseline-version=0

spring:
  datasource:
    url: jdbc:mariadb://velog.cqa7rhjwuoqr.ap-northeast-2.rds.amazonaws.com/cavel
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 147asdfg
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update