on:
  push:
    branches:
      - master
      - develop
env:
  S3_BUCKET_NAME: potato-velog-sunjo
  PROJECT_NAME: deploy

name: deploy to ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2

      - name: Upload S3
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          ./velog_backend/build/libs/*.jar s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
